spring:
  datasource:
    url: jdbc:postgresql://autorack.proxy.rlwy.net:29319/railway
    username: postgres
    password: xvjqgpilVqKNnBwrFDyyRqvukbHdFPrc
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # validate | update | create | create-drop